import React from 'react';
import {
  Printer, PenTool, Building2, Smartphone, Upload, Box,
  GraduationCap, Heart, Trophy, Globe, Truck, FileText,
  HelpCircle, Star, MessageCircle, Ruler, Layout, Info,
  Briefcase, Handshake, Mail, Shield, Package, Shirt, Gift,
  Users, ShieldCheck, Sparkles, Zap, Palette, CreditCard,
  Clock, Award, Crown, DollarSign, TrendingUp, Settings,
  Wrench, BookOpen, Video, Calendar, CheckCircle, Headphones,
  FileSearch, BarChart3, Scissors, MapPin, BadgeCheck, Rocket,
  Lock, Phone, User, LogIn, Moon, Sun, Menu, X, LogOut, Bell, ShoppingCart, Search, SlidersHorizontal, Grid, List
} from 'lucide-react';

const iconMap: Record<string, React.ReactNode> = {
  Printer: <Printer size={20} className="text-blue-accent" />,
  PenTool: <PenTool size={20} className="text-blue-accent" />,
  Building2: <Building2 size={20} className="text-blue-accent" />,
  Smartphone: <Smartphone size={20} className="text-blue-accent" />,
  Upload: <Upload size={20} className="text-blue-accent" />,
  Box: <Box size={20} className="text-blue-accent" />,
  GraduationCap: <GraduationCap size={20} className="text-blue-accent" />,
  Heart: <Heart size={20} className="text-blue-accent" />,
  Trophy: <Trophy size={20} className="text-blue-accent" />,
  Globe: <Globe size={20} className="text-blue-accent" />,
  Truck: <Truck size={20} className="text-blue-accent" />,
  FileText: <FileText size={20} className="text-blue-accent" />,
  HelpCircle: <HelpCircle size={20} className="text-blue-accent" />,
  Star: <Star size={20} className="text-blue-accent" />,
  MessageCircle: <MessageCircle size={20} className="text-blue-accent" />,
  Ruler: <Ruler size={20} className="text-blue-accent" />,
  Layout: <Layout size={20} className="text-blue-accent" />,
  Info: <Info size={20} className="text-blue-accent" />,
  Briefcase: <Briefcase size={20} className="text-blue-accent" />,
  Handshake: <Handshake size={20} className="text-blue-accent" />,
  Mail: <Mail size={20} className="text-blue-accent" />,
  Shield: <Shield size={20} className="text-blue-accent" />,
  Package: <Package size={20} className="text-blue-accent" />,
  Shirt: <Shirt size={20} className="text-blue-accent" />,
  Gift: <Gift size={20} className="text-blue-accent" />,
  Users: <Users size={20} className="text-blue-accent" />,
  ShieldCheck: <ShieldCheck size={20} className="text-blue-accent" />,
  Sparkles: <Sparkles size={20} className="text-blue-accent" />,
  Zap: <Zap size={20} className="text-blue-accent" />,
  Palette: <Palette size={20} className="text-blue-accent" />,
  CreditCard: <CreditCard size={20} className="text-blue-accent" />,
  Clock: <Clock size={20} className="text-blue-accent" />,
  Award: <Award size={20} className="text-blue-accent" />,
  Crown: <Crown size={20} className="text-blue-accent" />,
  DollarSign: <DollarSign size={20} className="text-blue-accent" />,
  TrendingUp: <TrendingUp size={20} className="text-blue-accent" />,
  Settings: <Settings size={20} className="text-blue-accent" />,
  Wrench: <Wrench size={20} className="text-blue-accent" />,
  BookOpen: <BookOpen size={20} className="text-blue-accent" />,
  Video: <Video size={20} className="text-blue-accent" />,
  Calendar: <Calendar size={20} className="text-blue-accent" />,
  CheckCircle: <CheckCircle size={20} className="text-blue-accent" />,
  Headphones: <Headphones size={20} className="text-blue-accent" />,
  FileSearch: <FileSearch size={20} className="text-blue-accent" />,
  BarChart3: <BarChart3 size={20} className="text-blue-accent" />,
  Scissors: <Scissors size={20} className="text-blue-accent" />,
  MapPin: <MapPin size={20} className="text-blue-accent" />,
  BadgeCheck: <BadgeCheck size={20} className="text-blue-accent" />,
  Rocket: <Rocket size={20} className="text-blue-accent" />,
  Lock: <Lock size={20} className="text-blue-accent" />,
  Phone: <Phone size={20} className="text-blue-accent" />,
  User: <User size={20} className="text-blue-accent" />,
  LogIn: <LogIn size={20} className="text-blue-accent" />,
  Moon: <Moon size={20} className="text-blue-accent" />,
  Sun: <Sun size={20} className="text-blue-accent" />,
  Menu: <Menu size={20} className="text-blue-accent" />,
  X: <X size={20} className="text-blue-accent" />,
  LogOut: <LogOut size={20} className="text-blue-accent" />,
  Bell: <Bell size={20} className="text-blue-accent" />,
  ShoppingCart: <ShoppingCart size={20} className="text-blue-accent" />,
  Search: <Search size={20} className="text-blue-accent" />,
  SlidersHorizontal: <SlidersHorizontal size={20} className="text-blue-accent" />,
  Grid: <Grid size={20} className="text-blue-accent" />,
  List: <List size={20} className="text-blue-accent" />,
};

export { iconMap };
